"""empty message

Revision ID: 399db67ce136
Revises: 
Create Date: 2024-12-01 23:00:02.235261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399db67ce136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_hashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('predicted_class', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_hashes')
    # ### end Alembic commands ###
